/**
 * client/src/pages/policies/AccessibilityStatement.tsx
 */
import PolicyLayout from "./PolicyLayout";

const sections = [
  {
    title: "1. Our Commitment",
    body: `E-Quipped: Work is committed to ensuring that our Platform is accessible to everyone, including people with disabilities. We aim to conform to the **Web Content Accessibility Guidelines (WCAG) 2.1 Level AA** as published by the World Wide Web Consortium (W3C).`,
  },
  {
    title: "2. Current Accessibility Features",
    body: `We have implemented the following accessibility features across the Platform:

**Visual design**
- All text meets a minimum contrast ratio of 4.5:1 against its background (WCAG AA)
- Lesson content uses a high-contrast dark canvas with near-white text (contrast ratio > 7:1)
- Font sizes are specified in relative units (rem/em) and respect browser zoom settings up to 200%

**Navigation and interaction**
- All interactive elements are reachable via keyboard (Tab, Shift+Tab, Enter, Space, Arrow keys)
- Visible focus indicators are present on all interactive elements
- Skip-to-content links are available on all pages

**Content**
- All images include descriptive alt text
- Form inputs are associated with visible labels
- Error messages are descriptive and identify the affected field
- Page titles are unique and descriptive

**Assistive technology**
- Semantic HTML5 landmarks (header, main, nav, footer) are used throughout
- ARIA roles and attributes are used where native HTML semantics are insufficient
- The Platform has been tested with NVDA (Windows) and VoiceOver (macOS/iOS)`,
  },
  {
    title: "3. Known Limitations",
    body: `We are aware of the following areas that do not yet fully meet WCAG 2.1 AA:

- **AI sandbox chat interface** — live region announcements for streaming AI responses are not yet implemented. Screen reader users may need to navigate manually to read new messages.
- **Flashcard flip animation** — the card flip effect uses CSS 3D transforms that may be distracting for users with vestibular disorders. We plan to add a prefers-reduced-motion override in a future update.
- **PDF exports** — payment receipts generated by Stripe are not tagged PDFs. We recommend requesting an accessible alternative by emailing equippedbyxixvi@gmail.com.

We are actively working to address these limitations.`,
  },
  {
    title: "4. Technical Specification",
    body: `E-Quipped: Work is built with:

- **React 19** with semantic HTML5
- **Tailwind CSS 4** with WCAG-compliant colour tokens
- **shadcn/ui** component library, which follows WAI-ARIA patterns
- **Radix UI** primitives for accessible interactive components (dialogs, tabs, dropdowns)

The Platform relies on JavaScript for core functionality. We recommend using a modern browser with JavaScript enabled.`,
  },
  {
    title: "5. Feedback and Contact",
    body: `We welcome feedback on the accessibility of E-Quipped: Work. If you experience any barriers or have suggestions for improvement, please contact us:

**Email:** equippedbyxixvi@gmail.com
**Response time:** We aim to respond within 5 business days.

If you are not satisfied with our response, you may contact the relevant enforcement body in your country. In the UK, this is the Equality and Human Rights Commission (equalityhumanrights.com).`,
  },
  {
    title: "6. Assessment Approach",
    body: `E-Quipped Ltd assesses the accessibility of the Platform through:

- Self-evaluation against WCAG 2.1 AA success criteria
- Automated testing using Axe and Lighthouse
- Manual keyboard navigation testing
- Screen reader testing with NVDA and VoiceOver

We review accessibility as part of every major feature release.`,
  },
];

export default function AccessibilityStatement() {
  return (
    <PolicyLayout
      title="Accessibility Statement"
      subtitle="Our commitment to WCAG 2.1 AA and inclusive design"
      lastUpdated="23 February 2026"
      sections={sections}
    />
  );
}
